export const pipeline = [
  {
    id: "ml",
    label: "ML",
    full: "Machine Learning",
    color: "var(--green)",
    dim: "var(--green-dim)",
    desc: "Mathematical & statistical foundations. Gradient descent, loss functions, supervised learning.",
    icon: "⊕",
  },
  {
    id: "nlp",
    label: "NLP",
    full: "Text Data & NLP",
    color: "var(--blue)",
    dim: "var(--blue-dim)",
    desc: "Converting language into vectors. Tokenization, embeddings, sequence modeling.",
    icon: "≋",
  },
  {
    id: "llm",
    label: "LLM",
    full: "Attention / GPT",
    color: "var(--purple)",
    dim: "var(--purple-dim)",
    desc: "Transformer architecture. Self-attention, pretraining, fine-tuning.",
    icon: "◈",
  },
  {
    id: "rag",
    label: "RAG",
    full: "Retrieval-Augmented",
    color: "var(--accent)",
    dim: "var(--accent-dim)",
    desc: "LLM + knowledge base. Vector DB, semantic search, grounding.",
    icon: "⟨⟩",
  },
  {
    id: "agent",
    label: "Agent",
    full: "AI Agent",
    color: "var(--coral)",
    dim: "var(--coral-dim)",
    desc: "LLM + tools + memory + planning. ReAct, tool-use, agentic loops.",
    icon: "⌬",
  },
  {
    id: "multi",
    label: "Multi-agent",
    full: "Multi-agent Systems",
    color: "var(--pink)",
    dim: "var(--pink-dim)",
    desc: "Multiple agents coordinating. Orchestration, debate, specialization.",
    icon: "⬡",
  },
];

export const books = [
  {
    tag: "Foundation",
    tagColor: "var(--green)",
    tagDim: "var(--green-dim)",
    title: "Grokking Machine Learning",
    chapter: "Ch. 1",
    author: "Luis G. Serrano",
    role: "Build ML intuition through visuals & simple Python code. The ideal starting point before diving into deep learning.",
    covers: ["Supervised learning", "Gradient descent", "Loss functions"],
  },
  {
    tag: "Architecture",
    tagColor: "var(--purple)",
    tagDim: "var(--purple-dim)",
    title: "Build a Large Language Model From Scratch",
    chapter: "Ch. 1",
    author: "Sebastian Raschka",
    role: "Code GPT from scratch — tokenizer, attention, pretraining. Essential for truly understanding transformer internals.",
    covers: ["Attention mechanism", "Token prediction", "GPT internals"],
  },
  {
    tag: "Production",
    tagColor: "var(--blue)",
    tagDim: "var(--blue-dim)",
    title: "AI Engineering",
    chapter: "Ch. 1",
    author: "Chip Huyen",
    role: 'Real-world engineering perspective: deployment, evaluation pipelines, latency, cost. From "it works" to "it works in production".',
    covers: ["Evaluation mindset", "Production systems", "Model deployment"],
  },
  {
    tag: "Landscape",
    tagColor: "var(--accent)",
    tagDim: "var(--accent-dim)",
    title: "AI Agents and Applications",
    chapter: "Ch. 1",
    author: "Multiple Authors",
    role: "Comprehensive map of the agent ecosystem: tool use, planning, memory types. Read before coding to stay on track.",
    covers: ["Tool use", "Memory systems", "Agent taxonomy"],
  },
  {
    tag: "Hands-on",
    tagColor: "var(--coral)",
    tagDim: "var(--coral-dim)",
    title: "AI Agents in Action",
    chapter: "Ch. 1",
    author: "Manik Mehta",
    role: "From theory to real agent systems with LangChain & modern frameworks. Real code, real problems.",
    covers: ["LangChain", "ReAct pattern", "Multi-agent build"],
  },
];

export const focusAreas = [
  { label: "AI vs ML vs Deep Learning", group: "concept" },
  { label: "Foundation Models", group: "concept" },
  { label: "LLMs", group: "concept" },
  { label: "NLP", group: "concept" },
  { label: "RAG", group: "system" },
  { label: "Agents", group: "system" },
  { label: "Multi-agent Systems", group: "system" },
  { label: "Evaluation Mindset", group: "mindset" },
  { label: "Production Mindset", group: "mindset" },
];

export const hardestPhase = {
  name: "Agent & Multi-agent",
  phase: "Phase 3 — Hardest",
  color: "var(--coral)",
  reasons: [
    "No fixed architecture — each system is a new design problem",
    "Debugging emergent behavior is hard to reproduce consistently",
    "Requires solid understanding of all 5 prior layers: ML → NLP → LLM → RAG → Agent",
    "Orchestration and conflict resolution between agents has no standard playbook",
  ],
};
